### ISSUE TITLE
Create generic QR code scanner

### ISSUE THREAD

**Issue by jsome635** [ambientlab-immersivelearning/ImmersiveLearning#2]
All work that is done for this task will be in a in a branch called issue-XX, where XX is the issue number.

# What needs to be accomplished
Follow tutorials to create QR code scanner.

There should be tutorials on various methods to scan QR codes. The ZXing library can be used to scan both 1D (barcode) and 2D (Qr code) images. Unity might have a library or Asset Store download that can readily scan QR codes. Microsoft documentation suggests that there is a plugin called QRTracking that can also be used for similar purposes.

Close the issue once completed and move to 'Waiting for merge' in Project.

**Comment by g-tolentino** [comment]
Finished and tested on HoloLens. Was able to read a 1"x1" QR code on my phone that was about an arms length away. Also noticed you need to look at QR code straight on to get a reading.
